### ISSUE TITLE
Compilation issue from rocthrust library on ROCm-3.5.

### ISSUE THREAD

**Issue by SaurabhKavi** [ROCmSoftwarePlatform/rocThrust#116]
Hi all,
I have successfully build and tested my application with HCC(ROCm-3.3). Now, I am trying to build my app with hip-clang(ROCm-3.5) as HCC is deprecated but, I am getting compilation issues because of the rocThrust library. The thrust device system is getting selected as CUDA but it should be HIP.
I am attaching two files for further details.

- [FLOW.txt](https://github.com/ROCmSoftwarePlatform/rocThrust/files/4752135/FLOW.txt) for compilation flow &
- [version detail.txt](https://github.com/ROCmSoftwarePlatform/rocThrust/files/4752136/version.detail.txt) for hip version related details.

I would like to know, how can i resolve this issue as i am unable to do so. If some more details are required please let me know.

Best regards,
Saurabh.

**Comment by saadrahim** [comment]
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__= 
I am not sure why you leave that blank.
I suspect something is wrong in the platform and compiler detection. What OS are you running on?

**Comment by SaurabhKavi** [comment]
Hi,
I am using rocm-3.5 docker based on Ubuntu-18.04.1.
Yes, i think there is a problem in compiler detection. 
THRUST_DEVICE_COMPILER == THRUST_DEVICE_COMPILER_HCC condition is not getting passed as I see.
I have not made any changes to  CPP_CONFIG. In my rocm-3.3 system it is showing CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=   -I/opt/rocm-3.3.0/hip/include -I/opt/rocm/hcc/include -I/opt/rocm/hsa/include

Could you suggest any quick fix for this.

Thanks.

**Comment by SaurabhKavi** [comment]
Hi @saadrahim 
When can i expect a fix for this, or is it from my side that i need to do any correction. Please let me know.

Best Regards
Saurabh

**Comment by saadrahim** [comment]
Hi Saurabh,
I don't have an ETA for you. A developer is assigned to this. Updates will follow.
Saad

**Comment by neon60** [comment]
Hi Saurabh,

As you can see, we set the `THRUST_DEVICE_COMPILER_HCC` at the following line:
https://github.com/ROCmSoftwarePlatform/rocThrust/blob/develop/thrust/detail/config/compiler.h#L83-L85

Based on the error message it looks like you have to set `HIP_PLATFORM=hcc` and `HIP_COMPILER=clang` which should be set automatilcally, when you are using HIP-clang (/opt/rocm/bin/hipcc)
Could you try to build rocThrust with the following command:
Option A:
`mkdir build && cd build`
`CXX=hipcc cmake -DBUILD_TEST=ON ../.`
`make -j`

Option B:
`mkdir build && cd build`
`cmake -DCMAKE_CXX_COMPILER=hipcc -DBUILD_TEST=ON ../.`
`make -j`

Option C:
`mkdir build && cd build`
`cmake -DCMAKE_CXX_COMPILER=hipcc -DHIP_COMPILER=clang -DHIP_PLATFORM=hcc -DBUILD_TEST=ON ../.`
`make -j`

If it's still try to build with CUDA backend, please send us the output of the cmake commands. It should work with all three options and at normal case, you do not have to set `HIP_COMPILER` and `HIP_PLATFORM`.

Thanks. Best regards,
Istvan Kiss

**Comment by SaurabhKavi** [comment]
Hi Istvan,

I did a clean build of rocThrust accordingly as you have mentioned above with different options A,B,C. 
I observed that the thrust system is still trying to build with cuda backend, because of which the compilation failed. I am attaching the _cmake_ and _make_ logs of the rocThrust build. Hope it helps in resolving the issue.

[cmake_optionA_log.txt](https://github.com/ROCmSoftwarePlatform/rocThrust/files/4824957/cmake_optionA_log.txt)
[cmake_optionB_log.txt](https://github.com/ROCmSoftwarePlatform/rocThrust/files/4824959/cmake_optionB_log.txt)
[cmake_optionC_log.txt](https://github.com/ROCmSoftwarePlatform/rocThrust/files/4824960/cmake_optionC_log.txt)
[make_optionA_log.txt](https://github.com/ROCmSoftwarePlatform/rocThrust/files/4824961/make_optionA_log.txt)
[make_optionB_log.txt](https://github.com/ROCmSoftwarePlatform/rocThrust/files/4824964/make_optionB_log.txt)
[make_optionC_log.txt](https://github.com/ROCmSoftwarePlatform/rocThrust/files/4824965/make_optionC_log.txt)


Please let me know if I missed something.

Thanks. Regards,
Saurabh

**Comment by neon60** [comment]
Hi Saurabh,

Based on the output of the make commands, you could build the rocThrust tests with HIP backend. It looks like the problem in the rocThrust integration of you application or the building flags of your application. The example how to integrate rocThrust to your application can be find under the following link:
https://github.com/ROCmSoftwarePlatform/rocThrust/blob/develop/extra/CMakeLists.txt

In the CI file you can see examples, how we build this simple test which depends on rocThrust:
https://github.com/ROCmSoftwarePlatform/rocThrust/blob/develop/.gitlab-ci.yml#L107-L113

You can also build your own packages, if you want to use the latest rocThrust:
https://github.com/ROCmSoftwarePlatform/rocThrust/blob/develop/.gitlab-ci.yml#L81-L93

If you can share, how you integrated to your application and how you build, we can help.

Thanks. Best regards,
Istvan Kiss

**Comment by saadrahim** [comment]
@SaurabhKavi Please let us know if this issue is active. I will close the ticket in a week otherwise.

**Comment by SaurabhKavi** [comment]
Hi @saadrahim @neon60 
Thanks for the help. Unfortunately the issue is still there for me. I wasn't able to work on this issue for some time. I will update or reopen the ticket if required.

Best Regards
Saurabh

**Comment by SaurabhKavi** [comment]
Hi @saadrahim @neon60 
This rocthrust error was resolved on ROCm-3.5 after i changed the files extension from .c to .hip/.cpp . I found out that the reason for this was Hip-clang does not consider .c files as HIP sources, so it compiles them as CPU-only files. 
But on ROCm-3.7, I am facing the same issue now. 
I am using rocThrust 2.10.3. Below is the detail. 
-- ******** Summary ********
-- General:
--   System                : Linux
--   HIP ROOT              :
--   C++ compiler          : /opt/rocm/bin/hipcc
--   C++ compiler version  : 11.0.0
--   CXX flags             : -Wno-unused-command-line-argument -Wall -Wextra -Wno-unused-function
--   Build type            : Release
--   Install prefix        : /opt/rocm
--   Device targets        : gfx803;gfx900;gfx906;gfx908
--
--   DISABLE_WERROR        : ON
--   DOWNLOAD_ROCPRIM      : OFF
--   BUILD_TEST            : ON
--   BUILD_EXAMPLES        : OFF
--   BUILD_BENCHMARKS      : OFF

I don't understand why HIP ROOT is empty. Could this be a reason for the error which i am getting.

Best regards,
Saurabh.

**Comment by SaurabhKavi** [comment]
Hi @saadrahim @neon60
This rocthrust error was resolved on ROCm-3.5 after i changed the files extension from .c to .hip/.cpp . I found out that the reason for this was Hip-clang does not consider .c files as HIP sources, so it compiles them as CPU-only files. 
But on ROCm-3.7, I am facing the same issue now. 
I am using rocThrust 2.10.3. Below is the detail. 
-- ******** Summary ********
-- General:
--   System                : Linux
--   HIP ROOT              :
--   C++ compiler          : /opt/rocm/bin/hipcc
--   C++ compiler version  : 11.0.0
--   CXX flags             : -Wno-unused-command-line-argument -Wall -Wextra -Wno-unused-function
--   Build type            : Release
--   Install prefix        : /opt/rocm
--   Device targets        : gfx803;gfx900;gfx906;gfx908
--
--   DISABLE_WERROR        : ON
--   DOWNLOAD_ROCPRIM      : OFF
--   BUILD_TEST            : ON
--   BUILD_EXAMPLES        : OFF
--   BUILD_BENCHMARKS      : OFF

I don't understand why HIP ROOT is empty. Could this be a reason for the error which i am getting.

Best regards,
Saurabh.

**Comment by SaurabhKavi** [comment]
Hi @saadrahim @neon60
This rocthrust error I was resolved on ROCm-3.5 after I changed the files extension from .c to .hip/.cpp . I found out that the reason for this was Hip-clang does not consider .c files as HIP sources, so it compiles them as CPU-only files.
But on ROCm-3.7, I am facing the same issue now.
I am using rocThrust 2.10.3. Below is the detail.
--   System                : Linux
--   HIP ROOT              :
--   C++ compiler          : /opt/rocm/bin/hipcc
--   C++ compiler version  : 11.0.0
--   CXX flags             : -Wno-unused-command-line-argument -Wall -Wextra -Wno-unused-function
--   Build type            : Release
--   Install prefix        : /opt/rocm
--   Device targets        : gfx803;gfx900;gfx906;gfx908
--   DISABLE_WERROR        : ON
--   DOWNLOAD_ROCPRIM      : OFF
--   BUILD_TEST            : ON
--   BUILD_EXAMPLES        : OFF
--   BUILD_BENCHMARKS      : OFF

I don't understand why HIP ROOT is empty. Could this be a reason for the error which i am getting?

Best regards,
Saurabh.

**Comment by SaurabhKavi** [comment]
Hi @saadrahim @neon60
This rocthrust error I was able to resolve on ROCm-3.5 after I changed the files extension from .c to .hip/.cpp . I found out that the reason for this was Hip-clang does not consider .c files as HIP sources, so it compiles them as CPU-only files.
But on ROCm-3.7, I am facing the same issue now.
I am using rocThrust 2.10.3. Below is the detail.
--   System                : Linux
--   HIP ROOT              :
--   C++ compiler          : /opt/rocm/bin/hipcc
--   C++ compiler version  : 11.0.0
--   CXX flags             : -Wno-unused-command-line-argument -Wall -Wextra -Wno-unused-function
--   Build type            : Release
--   Install prefix        : /opt/rocm
--   Device targets        : gfx803;gfx900;gfx906;gfx908
--   DISABLE_WERROR        : ON
--   DOWNLOAD_ROCPRIM      : OFF
--   BUILD_TEST            : ON
--   BUILD_EXAMPLES        : OFF
--   BUILD_BENCHMARKS      : OFF

I don't understand why HIP ROOT is empty. Could this be a reason for the error which i am getting ?

Best regards,
Saurabh.

**Comment by saadrahim** [comment]
Starting with rocm 3.5, you need to add  -x hip to signify that a file container hip source code.

**Comment by SaurabhKavi** [comment]
Thanks @saadrahim for the input. It now works perfectly on ROCm-3.7

Regards
Saurabh

**Comment by aurotripathy** [comment]
> Starting with rocm 3.5, you need to add -x hip to signify that a file container hip source code.

I hav the same issue. Where do we add this "-x hip"?
