### ISSUE TITLE
CMake issue when mixing Fortran/c++

### ISSUE THREAD

**Issue by pghysels** [ROCmSoftwarePlatform/rocThrust#149]
I'm trying to build a library using roc::rocthrust. I have the following lines in my CMakeLists.txt
```
...
find_package(rocprim REQUIRED)
find_package(rocthrust REQUIRED)
...
target_link_libraries(strumpack PUBLIC roc::hipblas roc::rocblas roc::rocsolver roc::rocthrust)
```

The problem is that the roc::rocthrust target also adds flags to the fortran compilation commands:
> gfortran: error: unrecognized command line option ‘--hip-device-lib-path=/opt/rocm-3.8.0/lib’
> gfortran: error: unrecognized command line option ‘--cuda-gpu-arch=gfx900’
> gfortran: error: unrecognized command line option ‘--cuda-gpu-arch=gfx906’

**Comment by saadrahim** [comment]
Thank you for reporting this issue. Apologies for the delay. I will take a look at getting this issue assigned internally.

**Comment by pghysels** [comment]
Thank you!
It seems that with ROCm 3.9, I no longer need rocThrust since std::complex operations are natively supported in HIP kernels, is that correct?

**Comment by pghysels** [comment]
I still have this issue with ROCm 3.10

**Comment by saadrahim** [comment]
Please see https://github.com/ROCm-Developer-Tools/HIP/pull/2183.

That PR will resolve the Fortran cmake issues in a future release.

**Comment by saadrahim** [comment]
Resolved as per previous comment.
