### ISSUE TITLE
Apps/sample code using rocThrust

### ISSUE THREAD

**Issue by brad-mengchi** [ROCmSoftwarePlatform/rocThrust#183]
Hi all,

I am looking at rocThrust library. Are there any open-source workloads/benchmarks/applications or sample codes that directly using rocThrust?

Thanks

**Comment by saadrahim** [comment]
Have you looked in https://github.com/ROCmSoftwarePlatform/rocThrust/tree/develop/examples?

**Comment by brad-mengchi** [comment]
Oh I did not notice that. Thanks a lot!
