### ISSUE TITLE
inclusive_scan_by_key does not compile if HIP_TEMPLATE_KERNEL_LAUNCH is defined

### ISSUE THREAD

**Issue by Oblomov** [ROCmSoftwarePlatform/rocThrust#242]
Hello,

this is illustrated by trying to compile this 4-liner
```c++
#define HIP_TEMPLATE_KERNEL_LAUNCH
#include <thrust/device_vector.h>
device_ptr<float4> a;
device_ptr<uint> b : c < inclusive_scan_by_key(b, b, a, a);
```
obtained by applying Creduce to a larger piece of code.

With `HIP_TEMPLATE_KERNEL_LAUNCH`, this fails with:

    error: no matching function for call to 'hipLaunchKernelGGL

Without the define, `inclusive_scan_by_key` compiles correctly. This is a regression since in the past (at least in 4.2.0) this used to work.

**Comment by Maetveis** [comment]
Hi, this turned out to be an issue in rocPRIM that rocThrust uses internally to implement `scan_by_key`. Could you try if installing https://github.com/ROCmSoftwarePlatform/rocPRIM/pull/342 fixes the issue for you?

**Comment by Oblomov** [comment]
From a quick check it seems to work. With the patch applied I can build my code with `HIP_TEMPLATE_KERNEL_LAUNCH`.
