### ISSUE TITLE
How to compile a program using rocThrust on Ubuntu 20.04?

### ISSUE THREAD

**Issue by sampie** [ROCmSoftwarePlatform/rocThrust#244]
On Ubuntu 20.04 system with rocm 5.2 compiling code using rocThrust fails (Score.cpp has "#include <thrust/host_vector.h>" which causes compile to fail):

clang++  -D__HIP_PLATFORM_HCC__= -D__HIP_PLATFORM_AMD__= -I/opt/rocm-5.2.0/include -I/opt/rocm-5.2.0/llvm/bin/../lib/clang/14.0.0 -I/opt/rocm-5.2.0/hsa/include -c -std=c++20 -g -O0 -pg Score.cpp 
In file included from Score.cpp:11:
In file included from /opt/rocm-5.2.0/include/thrust/host_vector.h:27:
In file included from /opt/rocm-5.2.0/include/thrust/detail/vector_base.h:25:
In file included from /opt/rocm-5.2.0/include/thrust/iterator/detail/normal_iterator.h:27:
In file included from /opt/rocm-5.2.0/include/thrust/iterator/iterator_adaptor.h:36:
In file included from /opt/rocm-5.2.0/include/thrust/iterator/iterator_facade.h:37:
In file included from /opt/rocm-5.2.0/include/thrust/iterator/detail/iterator_facade_category.h:22:
In file included from /opt/rocm-5.2.0/include/thrust/iterator/detail/device_system_tag.h:23:
In file included from /opt/rocm-5.2.0/include/thrust/system/cuda/detail/execution_policy.h:35:
/opt/rocm-5.2.0/include/thrust/system/cuda/config.h:33:10: fatal error: 'cub/util_namespace.cuh' file not found
#include <cub/util_namespace.cuh>
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by zjin-lcf** [comment]
It seems that 'hipCub' needs to installed first

**Comment by stanleytsang-amd** [comment]
Hi @sampie Sorry for the extreme delay in response.  If you are using clang directly, then you will need to pass -xhip to the compiler to specify that we are treating source files as HIP language files.  And also make sure that you do have rocprim installed in /opt/rocm as well.

**Comment by sampie** [comment]
It did upgrade Ubuntu to 22.04 and rocm to 5.3 and added -xhip parameter (rockprim is also installed), but did not manage to compile the file:

$ clang++  -D__HIP_PLATFORM_HCC__= -D__HIP_PLATFORM_AMD__= -I/opt/rocm-5.3.0/include -I/opt/rocm-5.3.0/llvm/bin/../lib/clang/15.0.0 -I/opt/rocm-5.3.0/hsa/include -xhip -fPIE -c -std=c++20 -g -O0 Score.cpp
lld: error: undefined symbol: __oclc_ABI_version
>>> referenced by /tmp/Score-fec864/Score-gfx803.o:(__ockl_hostcall_preview)
>>> referenced by /tmp/Score-fec864/Score-gfx803.o:(__ockl_hostcall_preview)
clang: error: amdgcn-link command failed with exit code 1 (use -v to see invocation)

**Comment by stanleytsang-amd** [comment]
I haven't encountered that error before.  The only reference I can find online to that is https://docs.olcf.ornl.gov/systems/crusher_quick_start_guide.html#olcfdev-1118-link-errors-with-rocm-5-2-0-and-cce.  As per that webpage, can you try using amdclang++ instead, located in /opt/rocm-5.3.0/bin?

**Comment by sampie** [comment]
It looks like amdclang++ works!! Perhaps normal clang does not fully yet support hip language.

**Comment by doctorcolinsmith** [comment]
Closing out as there is no reply from the user
