### ISSUE TITLE
Feature request: Add support for NAVI22 and NAVI23 i.e. gfx1031 and gfx1032

### ISSUE THREAD

**Issue by klausbu** [ROCmSoftwarePlatform/rocThrust#257]
Please add support for NAVI22 and NAVI23 i.e. gfx1031 and gfx1032 to enable HIP development leveraging rocThrust  on Notebooks as ALL AMD mobile GPUs are NAVI22 or NAVI23 i.e. gfx1031 or gfx1032.

Relevant engineering and scientific software uses Thrust. Porting this software to AMD hardware requires rocThrust support on development hardware. Please align with the rocPRIM developers as it`s a dependency.

My target operating system is RHEL9 = AlmaLinux 9, Rocky Linux ...

**Comment by doctorcolinsmith** [comment]
Navi22 and 23 are not officially supported in our distributed packages.  However, you can build from source for those platforms.
