### ISSUE TITLE
Fixing compile error: no member named 'init_offset_scan_state_kernel' ... ?

### ISSUE THREAD

**Issue by klausbu** [ROCmSoftwarePlatform/rocThrust#272]
When I try to compile rocThrust, I get an error: no member named 'init_offset_scan_state_kernel' ...

...
`In file included from /home/klaus/Programme/rocalution_install/rocThrust-rocm-5.1.3/thrust/../thrust/detail/scan.inl:29:
In file included from /home/klaus/Programme/rocalution_install/rocThrust-rocm-5.1.3/thrust/../thrust/system/detail/adl/scan_by_key.h:44:
In file included from /home/klaus/Programme/rocalution_install/rocThrust-rocm-5.1.3/thrust/../thrust/system/hip/detail/scan_by_key.h:36:
In file included from /home/klaus/Programme/rocalution_install/rocThrust-rocm-5.1.3/thrust/../thrust/system/hip/execution_policy.h:81:
/home/klaus/Programme/rocalution_install/rocThrust-rocm-5.1.3/thrust/../thrust/system/hip/detail/set_operations.h:956:61: error: no member named 'init_offset_scan_state_kernel' in namespace 'rocprim::detail'; did you mean 'init_lookback_scan_state_kernel'?
        hipLaunchKernelGGL(HIP_KERNEL_NAME(rocprim::detail::init_offset_scan_state_kernel),
                                           ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                            init_lookback_scan_state_kernel
/opt/rocm-5.4.0/include/hip/amd_detail/amd_hip_runtime.h:199:30: note: expanded from macro 'HIP_KERNEL_NAME'
#define HIP_KERNEL_NAME(...) __VA_ARGS__
                             ^~~~~~~~~~~
/opt/rocm-5.4.0/include/hip/amd_detail/amd_hip_runtime.h:251:74: note: expanded from macro 'hipLaunchKernelGGL'
#define hipLaunchKernelGGL(kernelName, ...)  hipLaunchKernelGGLInternal((kernelName), __VA_ARGS__)
                                                                         ^~~~~~~~~~
/opt/rocm-5.4.0/include/hip/amd_detail/amd_hip_runtime.h:248:9: note: expanded from macro 'hipLaunchKernelGGLInternal'
        kernelName<<<(numBlocks), (numThreads), (memPerBlock), (streamId)>>>(__VA_ARGS__);         \
        ^~~~~~~~~~
/opt/rocm-5.4.0/include/rocprim/device/detail/device_scan_common.hpp:76:60: note: 'init_lookback_scan_state_kernel' declared here
    __launch_bounds__(ROCPRIM_DEFAULT_MAX_BLOCK_SIZE) void init_lookback_scan_state_kernel(
                                                           ^
In file included from /home/klaus/Programme/rocalution_install/rocThrust-rocm-5.1.3/test/test_zip_iterator.cpp:18:
In file included from /home/klaus/Programme/rocalution_install/rocThrust-rocm-5.1.3/thrust/../thrust/copy.h:512:
`
...

This error comes up several times before the compile process is stopped.

I tested rocPRIM after the installation and all tests were successful.

How to approach this error? Is it rocPRIM related or rocThrust related?

**Comment by Snektron** [comment]
It seems you are using different versions of rocPRIM and rocThrust. rocThrust and rocPRIM, and in fact the entire ROCm stack, are designed to work together with the same version. I suggest to either downgrade rocPRIM to 5.1.3 or upgrade rocThrust to 5.4.0.

**Comment by doctorcolinsmith** [comment]
Based on @klausbu 's last comment, this appears to be resolved.
