### ISSUE TITLE
How can I set the path etc. to an alternative rocThrust installation to be used by the compiler?

### ISSUE THREAD

**Issue by klausbu** [ROCmSoftwarePlatform/rocThrust#273]
I installed architecture specific versions of rocPRIM and rocThrust in the subdirectory: 

/opt/rocm-5.4.0/myspecialrocm

When I try to compile an application for this architecture, the compiler picks the wrong version from the Linux distribution specific installation. When compiling rocThust itself, setting -DCMAKE_NO_SYSTEM_FROM_IMPORTED=TRUE and -DCMAKE_INSTALL_PREFIX=/opt/rocm-5.4.0/myspecialrocm did the trick.

How can I set the path etc. to this alternative rocThrust installation to be used by the compiler?

**Comment by vince-streamhpc** [comment]
If you're using Cmake you could use `[package]_DIR` or `[package]_ROOT` variables: https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure

If using the compiler directly, try `-isystem` ?

**Comment by doctorcolinsmith** [comment]
@klausbu Have you tried @vince-streamhpc's suggestion?

**Comment by doctorcolinsmith** [comment]
Closing as the user has not followed up.
