### ISSUE TITLE
looks like thrust::copy takes too much time.

### ISSUE THREAD

**Issue by LeiWang1999** [ROCmSoftwarePlatform/rocThrust#300]
I wrote a benchmark which random data generation partly base on rocThrust, the code can be accessed through 
https://github.com/LeiWang1999/rocblas-benchmark

From benchmarking, I found that the data generation took too much time on thrust::copy if the data size is arised at    
 
```
std::make_tuple(2048, 32768, 8192, false, false),
std::make_tuple(16384, 16384, 16384, false, false),
```

do you have any comments?

**Comment by Naraenda** [comment]
Hi, can you provide any extra details:
- What hardware are you running?
- What throughput are you expecting (GB/s)?

**Comment by LeiWang1999** [comment]
expect the speed as fast as nvidia-thrust, I'm using MI250
