### ISSUE TITLE
[Changelog] link not set on Requirements page 

### ISSUE THREAD

**Issue by ckime-amd** [ROCmSoftwarePlatform/rocThrust#323]
From https://rocm.docs.amd.com/projects/rocThrust/en/latest/setup/requirements.html:
please see the [CHANGELOG.md].

Not sure if Changelog is published to the docs site or the link should point to the GitHub repo version of the file.

**Comment by lawruble13** [comment]
Hey @ckime-amd, the link you listed there doesn't seem to exist anymore. There was a brief glitch in a different repository that caused some of our documentation to be incorrect, so can you please validate that this issue is still present, and if so provide an updated link?

**Comment by ckime-amd** [comment]
This was resolved with changes mad to address #324.
