### ISSUE TITLE
reference to __host__ function 'free'/'malloc' in __host__ __device__ function

### ISSUE THREAD

**Issue by jinz2014** [ROCmSoftwarePlatform/rocThrust#355]
Compiling a HIP program shows the following errors. Thanks for your suggestion.

```
In file included from /opt/rocm-6.0.0/include/thrust/system/detail/adl/malloc_and_free.h:26:
/opt/rocm-6.0.0/include/thrust/system/detail/sequential/malloc_and_free.h:45:8: error: reference to __host__ function 'free' in __host__ __device__ function
  std::free(thrust::raw_pointer_cast(ptr));


In file included from /opt/rocm-6.0.0/include/thrust/system/detail/adl/malloc_and_free.h:26:
/opt/rocm-6.0.0/include/thrust/system/detail/sequential/malloc_and_free.h:37:15: error: reference to __host__ function 'malloc' in __host__ __device__ function
  return std::malloc(n);
```

**Comment by doctorcolinsmith** [comment]
@jinz2014 Thanks for reporting the issue.  It is known to our team and we will follow up on it.

**Comment by jinz2014** [comment]
I didn't know the issue until migrating CUDA sources and building the HIP codes. If the CUDA sources are needed for your test, please let me know.

**Comment by doctorcolinsmith** [comment]
@jinz2014 If you have a reproducer you can share, we will include it in our testing.

**Comment by jinz2014** [comment]
In the example, 

https://github.com/zjin-lcf/HeCBench/tree/master/src/logic-rewrite-hip

Type "make" may reproduce the error.

**Comment by zichguan-amd** [comment]
Fixed in LLVM and works in latest ROCm

**Comment by jinz2014** [comment]
Is the latest ROCm available ?  Thanks.

**Comment by zichguan-amd** [comment]
You can find ROCm 6.2.2 installation steps here: https://rocm.docs.amd.com/projects/install-on-linux/en/develop/install/quick-start.html
