### ISSUE TITLE
[Feature]: Use `AnyNewerVersion` instead of `SameMajorVersion` for CMake compatibility

### ISSUE THREAD

**Issue by aprokop** [ROCmSoftwarePlatform/rocThrust#371]
### Suggestion Description

We've recently tried to build our library (ArborX) vs the newly release rocm 6.0 and rocthrust 3. We have 
```CMake
  find_package(rocthrust 2.10.5 REQUIRED CONFIG)
```
in our CMake config file. This fails for the new 3.0 rocthrust because it has `SameMajorVersion` compatibility mode.

I just wanted to check if that is intentional, or whether it could be switched to `AnyNewerVersion` so that downstream codes don't have to work around it.

**Comment by doctorcolinsmith** [comment]
Hello @aprokop.  Yes, updating the major version is intentional, there are some breaking API changes in that release.

**Comment by aprokop** [comment]
Good to know. Thank you for the quick reply.
