### ISSUE TITLE
[Documentation]: `thrust::hip::par_nosync`

### ISSUE THREAD

**Issue by mccoys** [ROCmSoftwarePlatform/rocThrust#411]
### Description of errors

I cannot find any description of the `thrust::hip::par_nosync` policy.

**Comment by umfranzw** [comment]
Hello, you can find a description of the ```par_nosync``` execution policy the changelog here: 

- https://github.com/ROCm/rocThrust/blob/develop/doc/CHANGELOG.md#new-thrustcudapar_nosync-execution-policy

By default, thrust API calls operate synchronously (they block). When this policy is used, thrust may launch some algorithms asynchronously if it is possible to do so (eg. if it does not affect the correctness of the output). This can result in improved performance. However, you'll need to explicitly synchronize after your API calls.

**Comment by mccoys** [comment]
Thank you for pointing this out. I still believe that a real documentation entry should be added. The changelog does not appear in search results

**Comment by umfranzw** [comment]
Agreed. It looks like this execution policy got missed in the documentation - probably because it was added after the others. I'll put up a pull request with a documentation update shortly.

**Comment by umfranzw** [comment]
Apologies for the long delay - the pull request is finally up here: https://github.com/ROCm/rocThrust/pull/421
