### ISSUE TITLE
How is rocThrust synchronized with the Nvidia version of Thrust?

### ISSUE THREAD

**Issue by correaa** [ROCmSoftwarePlatform/rocThrust#475]
that is the question.

If it is synchronized how of terms it is updated?

If this technically a fork? are updates to Thrust manually copied here? or is it automatic?

**Comment by Naraenda** [comment]
It's the thrust code-base ported over to ROCm, so a fork in the loosest sense as we do not share a commit history. Changes are manually copied over. There are unfortunately a few things that prevent us from directly building on-top of CCCL/thrust (like thrust being part of a monorepo).

**Comment by correaa** [comment]
Yes, I just noticed that Thrust is now part of a huge CCCL repository.
I guess that makes thing harder now.

So, you copy the core part of Thrust and add the Rocm backend part?

**Comment by Naraenda** [comment]
Yes. AFAIK, there are also some minor change to core thrust due to slight differences in defines the compiler (HIP/amdclang/cu) sets. I can poke someone else on the team if you need more details.

**Comment by ppanchad-amd** [comment]
Hi @correaa. Closing ticket as your questions have been answered. Please feel to comment if you require additional details. Thanks!
