### ISSUE TITLE
[Issue]: Build with Clang >= 19 and libc++ fails on _VSTD macro

### ISSUE THREAD

**Issue by AngryLoki** [ROCmSoftwarePlatform/rocThrust#478]
### Problem Description

Hi, 

`#include <thrust/type_traits/is_contiguous_iterator.h>` does not work with new versions of Clang when libc++ is enabled in compiler flags (i. e. `clang version 19.1.0+libcxx` `CXXFLAGS=--stdlib=libc++`).

The error is caused by lines:
https://github.com/ROCm/rocThrust/blob/6f47412b99e64a1d4681d9e0312132e4ad6042ec/thrust/type_traits/is_contiguous_iterator.h#L139-L144

Historical notes for _VSTD macro:
* Before Clang 14 it was defined as `std::_LIBCPP_ABI_NAMESPACE`
* [Clang 14 release notes](https://releases.llvm.org/14.0.0/projects/libcxx/docs/ReleaseNotes.html): "_VSTD is now an alias for std instead of std::_LIBCPP_ABI_NAMESPACE. This is technically not a functional change, except for folks that might have been using _VSTD in creative ways (which has never been officially supported)."
* Clang 19.1.0: _VSTD is fully removed as a part of [RFC proposal](https://discourse.llvm.org/t/rfc-clang-formatting-all-of-libc-once-and-for-all/75198) and https://github.com/llvm/llvm-project/pull/74331.

As seen on godbolt, `_VSTD` indeed was just `std` in Clang 17/18 - https://godbolt.org/z/nMWhj8PqT.

As ROCm stack effectively does not support anything earlier than Clang 17, is should be safe to replace `_VSTD` with `std`. Could you please replace one line?
```diff
-   _VSTD::__wrap_iter<Iterator>
+   std::__wrap_iter<Iterator>
```
That's _the only change_ required in rocThrust to fix compilation with Clang 19.1.0 (tested with pytorch). Thanks!

### Operating System

Gentoo

### CPU

-

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.2.2

### ROCm Component

rocThrust

**Comment by Naraenda** [comment]
Thanks for the report. The change from `_VSTD` to `std` was part of the CCCL 2.4 update. The ROCm 6.4 release should include compatibility/parity with 2.4 and also the requested change.

More specifically, it is fixed in https://github.com/ROCm/rocThrust/pull/462 in change https://github.com/ROCm/rocThrust/pull/462/commits/93b72cd8b9c6e53f1ac8067a83440736521d5c1f.
