### ISSUE TITLE
CMake dependency on rocprim missing

### ISSUE THREAD

**Issue by davidrohr** [ROCmSoftwarePlatform/rocThrust#61]
I have a program that builds v.s. rocthrust via CMake.

My build fails, because rocthrust links v.s. roc::rocprim_hip. (in rocthrust-targets.cmake)
So apparently, rocthrust depends on rocprim, but it doesn't require the rocprim package. I can fix this, by adding find_package(rocprim) to rocthrust-config.cmake.

And as a comment, I was a bit confused that the target is rocthrust and not roc::rocthrust, which is not really consistent e.g. with roc::rocprim.

**Comment by saadrahim** [comment]
Hi David,

Are you a first time user of rocThrust? I want to check if this issue appeared in the recent release or has existed for a while. 

I believe the rocthrust-targets.cmake file is missing some INTERFACE links. I will look at fixing this issue.

Best Regards,
Saad

**Comment by davidrohr** [comment]
Hi @saadrahim : It is the first time I used it.

Btw, In the meantime, I have also found that in the example you suggest to find both rocprim and rocthrust: https://github.com/ROCmSoftwarePlatform/rocThrust/blob/master/README.md#using-rocthrust-in-a-project
But to me, this is not intuitive. If rocthrust depends on rocprim, it should automatically detect it and add the dependency.

**Comment by saadrahim** [comment]
I apologize for the problem. There was a work around introduced for a particular high profile project that broke the cmake targets. I will have a better solution in place for the rocm-2.8 or 2.9 release (late August or September). It is too late for the 2.7 release candidate.

**Comment by saadrahim** [comment]
@neon60 Only thing left with this issue is to add the roc::rocthrust namespace.

**Comment by neon60** [comment]
https://github.com/ROCmSoftwarePlatform/rocThrust/pull/95

**Comment by saadrahim** [comment]
Will add find_package as the default mechanism to use rocPRIM.
