### ISSUE TITLE
Version of rocThrust compatible with older versions of ROCm?

### ISSUE THREAD

**Issue by mattsinc** [ROCmSoftwarePlatform/rocThrust#70]
I am attempting to run some benchmarks that use thrust in them through the gem5 simulator, which currently only supports ROCm 1.6.x.  While hipify'ing the applications, I need to port the thrust calls to use rocThrust (which I did).  However, after looking through the release tags and the commits for rocThrust, it appears that rocThrust only supports ROCm 2.5+.  Is this correct?  Or is there an (older) commit that has support for older versions of ROCm?

Thanks,
Matt

**Comment by saadrahim** [comment]
Hi Matt,
The rocThrust library is only supported on newer rocm releases. I recommend upgrading but it looks like you have no choice. Please try https://github.com/ROCmSoftwarePlatform/thrust. This is an unsupported library that will be archived soon. It may support an older rocm version.

**Comment by mattsinc** [comment]
Thanks @saadrahim   Yeah, unfortunately upgrading is not an option here.  Looking at that repo, I do see a branch for ROCm 1.5, so hopefully something there works for ROCm 1.6.  I'll check with them, thanks!

Matt
