### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by Dekken** [ROCmSoftwarePlatform/rocThrust#78]
If HCC is deprecated is this not also?

**Comment by saadrahim** [comment]
This library is not deprecated. There is an HCC based API versus a HIP based API. The HCC API is deprecated. The compiler HCC versus the HIPCC compiler are both supported. However, using the HIPCC compiler is recommend as the HCC compiler may be deprecated in the future.

**Comment by Dekken** [comment]
thanks I think I understand

rocThrust works with hipcc with rocPRIM
